  name: "test"
  platform: "onnxruntime_onnx"
  max_batch_size: 0
  input [
    {
      name: "input"
      data_type: TYPE_FP32
      dims: [ 2, 10 ]
    }
  ]
  output [
    {
      name: "output"
      data_type: TYPE_FP32
      dims: [ 2, 3 ]
    }
  ]